export const text = {
    userListHeader: 'User list',
    siteName: 'Admin dashboard',
    enterTheUsername: 'Enter the username',
    loadingUsers: 'Loading users',
    usersNotFound: 'Users were not found',
    viewPosts: 'View posts',
    zip: 'ZIP:',
    streetShort: 'st.',
    companyHeading: 'Company',
    userPosts: 'User posts',
    filter: 'Filters',
    applyFilters: 'Apply filters',
    postName: 'Post name',
    enterPostName: 'Enter post name',
    postAuthor: 'Post author',
    enterPostAuthor: "Enter post author's username",
    noPostsAvailable: 'No posts available',
    fetchingPosts: 'Finding posts',
    loadMore: 'Load more',
};
