export const text = {
    userListHeader: 'User list',
    siteName: 'Admin dashboard',
    enterTheUsername: 'Enter the username',
    loadingUsers: 'Loading users',
    usersNotFound: 'Users were not found',
    viewPosts: 'View posts',
    zip: 'ZIP:',
    streetShort: 'st.',
    companyHeading: 'Company',
    userPosts: 'User posts',
    filter: 'Filters',
    applyFilters: 'Apply filters',
    postName: 'Post name',
    enterPostName: 'Enter post name',
    postAuthor: 'Post author',
    enterPostAuthor: "Enter post author's username",
    noPostsAvailable: 'No posts available',
    fetchingPosts: 'Finding posts',
    loadMore: 'Load more',
    newPost: 'New post',

    CREATE_MODAL: {
        heading: 'Create the post',
        title: 'Title: ',
        content: 'Content: ',
        create: 'Create',
        writtenBy: 'Written by',
    },
    EDIT_MODAL: {
        heading: 'Edit the post',
        actionButtonText: 'Edit',
    },
    DELETE_MODAL: {
        heading: 'Delete post',
        warningText: 'Are you sure you want to delete the post?',
        yes: 'yes',
        no: 'no',
    },
    POST_PAGE: {
        heading: 'Post',
        invalidPostId: 'Could not find post',
        writtenBy: 'Written by',
    },
    COMMENTS_SECTION: {
        heading: 'Comments',
        newComment: 'New comment',
        deleteComment: 'Delete comment',
        areYouSure: 'Are you sure you want to delete comment?',
        editComment: 'Edit comment',
        edit: 'edit',
        delete: 'delete',
        title: 'Name:',
        email: 'Email:',
        content: 'Content: ',
        create: 'Create',
        noCommentsFound: 'No comments found',
    },
};
